name: "Issue Report"
description: "Report a bug and the steps to reproduce it"
labels: ["needs review","bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report! Please fill out this form as completely as possible.

  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A concise description of what you're experiencing.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps or code snippets to reproduce the behavior.
    validations:
      required: false

  - type: dropdown
    id: platform
    attributes:
      label: What platform(s) does this occur on?
      multiple: true
      options:
        - Web
        - Mobile
    validations:
      required: true

  - type: dropdown
    id: wallet
    attributes:
      label: Which wallet(s) does this occur on?
      multiple: true
      options:
        - Metamask
        - Coinbase Wallet
        - Rainbow
        - WalletConnect
        - Others
    validations:
      required: true      

  - type: dropdown  
    id: browsers
    attributes:
      label: What browser(s) does this occur on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Brave
        - Safari
        - Edge
        - In-wallet browser
        - Others
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: "Operating System(s)"
      multiple: true
      options:
        - Windows
        - MacOS
        - Linux
        - iOS
        - Android
    validations:
      required: true              

  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      multiple: true
      options:
        - Low
        - Medium
        - High
        - Critical        
    validations:
      required: true              

  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Screenshots? Anything that will give us more context about the issue you are encountering!
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
